added possibility to sort saved wordpairs
nyko27/flutter_labs pull request #1
Opened 2021-09-23 12:18 UTC by nyko27

Added button which allows user sort word pairs alphabetically that he previously marked as saved.

2021-09-23 12:28 UTC, Markot96 approved these changes
Great changes! You can merge

2021-09-23 13:59 UTC, Marchuk773 requested changes
Remove code duplication in map function

2021-09-27 09:21 UTC, igor-leshkevych reviewed
> Remove code duplication in map function

nice catch, but when your comment is related to a particular block of code, it's better to use an inline comment (so it is attached to that block)

2021-09-27 09:21 UTC, igor-leshkevych commented on lib/main.dart
> +                  (WordPair pair) {
use lambda funcation to save your selector to a separate variable, and then reuse it in both clauses:
```
final tiles = _sorted.isNotEmpty ? _sorted.map(selector) : _saved.map(selector)
```

2021-09-27 09:22 UTC, igor-leshkevych commented
@nyko27 please attach some screenshots

2021-09-28 17:21 UTC, nyko27 commented
> please attach some screenshots

@igor-leshkevych 



Saved word pairs before being sorted.

![image](https://user-images.githubusercontent.com/56033979/135133970-80c5d2bb-81ac-4ac6-94ba-022ad2f6a52a.png)




Saved word pairs after user pressed button(top right corner) "Sort saved".

![image](https://user-images.githubusercontent.com/56033979/135134718-917844d3-1b91-46a0-9322-751575e73e42.png)

2021-09-29 16:22 UTC, igor-leshkevych commented
@nyko27 

it's better to edit PR description and insert screenshots there rather than adding a new message to conversation. 

+5/5 hello world
+3/3 custom feature + PR

2021-10-11 14:19 UTC, merged